Feat: Add Cloud API test job to scheduled pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,7 +8,6 @@ variables:
   NSPECT_ID: NSPECT-K66V-JJ0K
   DOCKER_IMG: nvmetal-carbide
 
-
   FORGE_ADMIN_CLI_IMAGE: nvcr.io/nvidian/nvforge-devel/forge-admin-cli
   APPLICATION_DOCKER_IMAGE: nvcr.io/nvidian/nvforge-devel/nvmetal-carbide
   ARTIFACTS_DOCKER_IMAGE_AARCH64: nvcr.io/nvidian/nvforge-devel/boot-artifacts-aarch64
@@ -18,7 +17,7 @@ variables:
   ARTIFACTS_DOCKER_IMAGE_AARCH64_PRODUCTION: nvcr.io/nvidian/nvforge/boot-artifacts-aarch64
   ARTIFACTS_DOCKER_IMAGE_X86_64_PRODUCTION: nvcr.io/nvidian/nvforge/boot-artifacts-x86_64
 
-  FORGE_ADMIN_CLI_DOCKER_IMAGE: nvcr.io/nvidian/nvforge/forge-admin-cli
+  TEST_API_IMAGE: stg.nvcr.io/rkafbrtf9ezb/test-api
 
   FF_USE_FASTZIP: "true" # enable fastzip - a faster zip implementation that also supports level configuration.
   ARTIFACT_COMPRESSION_LEVEL: default # can also be set to fastest, fast, slow and slowest. If just enabling fastzip is not enough try setting this to fastest or fast.
@@ -1018,3 +1017,62 @@ scheduled-test:verify-site-controller-version:
         echo "Expected version ${LATEST_COMMON_VERSION} on site ${SITE_UNDER_TEST}, actual version is ${DEPLOYED_VERSION}";
         exit 1
       fi
+
+#
+# Run cloud-api sanity tests against the site under test.
+# The image is built in repo: https://gitlab-master.nvidia.com/cloud-service-qa/test-image
+# The test code is in repo: https://gitlab-master.nvidia.com/compute-swqa/cuda-automation-infra/tesla_automation_test/-/tree/main/Forge/tests/Forge_Testing/CommonTestSteps/API
+#
+scheduled-test:run-cloud-api-tests:
+  needs:
+    - job: scheduled-test:auto-deploy-site-controller
+    - job: scheduled-test:verify-site-controller-version
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+  timeout: 2h
+  retry:
+    when:
+      - runner_system_failure
+    max: 2
+  variables:
+    CARBIDE_API_URL: $CARBIDE_API_URL
+    PROJECT: forge
+    COMPONENT: api
+    SCOPE: site-sanity
+    VAULT_ADDR: https://prod.vault.nvidia.com
+    VAULT_NAMESPACE: ngc-forge
+  image:
+    name: $TEST_API_IMAGE
+    entrypoint: [ "" ]
+  before_script:
+    - set -euo pipefail
+    # Cannot overwrite predefined GitLab variables using the 'variables' section, so do it here:
+    - export VAULT_JWT_PATH="auth/jwt/nvidia/gitlab-master/login"
+    - export VAULT_JWT_ROLE="gitlab-ci"
+    - export VAULT_TOKEN="$(vault write -field=token $VAULT_JWT_PATH role=$VAULT_JWT_ROLE jwt=$CI_JOB_JWT)"
+    - export API_TOKEN=$(vault kv get -field nvcr secrets/forge/tokens)
+    - echo "[GENERAL]" > machine.config
+    - echo "api_endpoint = \"https://api.ngc.nvidia.com\"" >> machine.config
+    - echo "forge_url = \"https://forge.ngc.nvidia.com/\"" >> machine.config
+    - echo "ngc_auth = \"https://ngc.authn.nvidia.com/token?service=ngc&scope=group/ngc\"" >> machine.config
+    - echo "[GENERAL.ProviderAdmin]" >> machine.config
+    - echo "org = \"forge-prime-provider\"" >> machine.config
+    - echo "org_id = \"qpbftykv9atm\"" >> machine.config
+    - echo "token = \"$API_TOKEN\"" >> machine.config
+    - echo "[GENERAL.TenantAdmin]" >> machine.config
+    - echo "org = \"forge-tenant-dev\"" >> machine.config
+    - echo "org_id = \"i1k1exmxlqr1\"" >> machine.config
+    - echo "token = \"$API_TOKEN\"" >> machine.config
+    - echo "[ENV]" >> machine.config
+    - echo "site = \"demo01\"" >> machine.config
+    - export ENV="$(python -c 'import toml; print(toml.load("machine.config"))')"
+  script:
+    - /usr/bin/dumb-init -- /root/entrypoint.sh
+  after_script:
+    # Clean up the execution log by stripping out the ANSI escape codes
+    - sed -i -r "s/\x1B\[[0-9;]*[JKmsu]//g" /root/.tesla_linux_auto/task_run/TR1/execution.log
+    - mv /root/.tesla_linux_auto/task_run ${CI_PROJECT_DIR}
+  artifacts:
+    paths:
+      - task_run/
+    when: always
