feat: Add scheduled-test pipeline (initial stage)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,9 @@
+#
+# NOTE: Any new jobs not related to the scheduled testing pipeline should have the following
+# included as the first rule to prevent them being pulled in to the scheduled pipeline:
+#   - if: $CI_PIPELINE_SOURCE == "schedule"
+#     when: never
+
 variables:
   NSPECT_ID: NSPECT-K66V-JJ0K
   DOCKER_IMG: nvmetal-carbide
@@ -49,6 +55,7 @@ variables:
   CONTAINER_BUILD_ARTIFACTS_X86_64: "urm.nvidia.com/swngc-ngcc-docker-local/forge/carbide/x86-64/build-artifacts-container:latest"
   CONTAINER_ARTIFACTS_X86_64: "alpine:latest"
   CONTAINER_ARTIFACTS_AARCH64: "alpine:latest"
+  CONTAINER_SITE_AUTO_DEPLOY: "urm.nvidia.com/swngc-ngcc-docker-local/forge/carbide/tools/site-auto-deploy-container:latest"
 
 include:
   - project: "nvmetal/ci-tools/build-container-cocogitto"
@@ -69,6 +76,8 @@ include:
 
 prepare-ci:
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       needs:
         - job: "lint:commit-merge-request"
@@ -143,6 +152,8 @@ build-build-container-x86_64:
     - echo "CONTAINER_BUILD_X86_64=$CONTAINER_REGISTRY_X86_64/build-container:$VERSION" > build-container-x86_64.env
     - echo "CONTAINER_BUILD_X86_64_WAS_BUILT=true" >> build-container-x86_64.env
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
     - changes:
         - dev/docker/Dockerfile.build-container-x86_64
@@ -173,6 +184,8 @@ build-build-container-aarch64:
   tags:
     - aarch64
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
     - changes:
         - dev/docker/Dockerfile.build-container-aarch64
@@ -199,6 +212,8 @@ build-artifacts-build-container-x86_64:
     - echo "CONTAINER_BUILD_ARTIFACTS_X86_64=$CONTAINER_REGISTRY_X86_64/build-artifacts-container:$VERSION" > build-artifacts-container-x86_64.env
     - echo "CONTAINER_BUILD_ARTIFACTS_X86_64_WAS_BUILT=true" >> build-artifacts-container-x86_64.env
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
     - changes:
         - dev/docker/Dockerfile.build-artifacts-container-x86_64
@@ -229,6 +244,8 @@ build-artifacts-build-container-aarch64:
   tags:
     - aarch64
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
     - changes:
         - dev/docker/Dockerfile.build-artifacts-container-aarch64
@@ -252,6 +269,8 @@ build-runtime-container-x86_64:
     DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.runtime-container-x86_64
     BUILD_DOCKER_IMAGE: urm.nvidia.com/swngc-ngcc-docker-local/forge/$CI_PROJECT_NAME/x86-64/runtime-container
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
     - changes:
         - dev/docker/Dockerfile.runtime-container-x86_64
@@ -281,6 +300,8 @@ build-runtime-container-aarch64:
 #    - if: $CI_COMMIT_MESSAGE =~ /ci-rebuild-base-containers/
 #    - changes:
 #        - dev/docker/Dockerfile.runtime-container-aarch64
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
   after_script:
     - echo "CONTAINER_RUNTIME_AARCH64=$CONTAINER_REGISTRY_AARCH64/runtime-container:$VERSION" > runtime-container-aarch64.env
     - echo "CONTAINER_RUNTIME_AARCH64_WAS_BUILT=true" >> runtime-container-aarch64.env
@@ -347,6 +368,8 @@ tag-build-and-runtime-containers:
     fi
 
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
 
 #
@@ -380,6 +403,8 @@ build-release-container-x86_64:
         fi
     - docker rmi intermediate-container-$CI_COMMIT_SHORT_SHA
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
       variables:
         DEPLOY_BUILT_CONTAINER: "true"
@@ -399,6 +424,10 @@ build-release-container-x86_64:
   stage: build
   variables:
     FORGE_CA: "prod"
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
+    - when: always
 
 build-boot-artifacts-x86_64:
   extends: .build-boot-artifacts
@@ -501,6 +530,8 @@ build-release-artifacts-x86_64:
           echo "Skipping deployment of intermediate-artifacts-$CI_COMMIT_SHORT_SHA"
         fi
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
       variables:
         DEPLOY_BUILT_CONTAINER: "true"
@@ -547,6 +578,8 @@ build-release-artifacts-aarch64:
       /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" --build-arg "CONTAINER_RUNTIME_AARCH64=$CONTAINER_ARTIFACTS_X86_64" --no-push
     fi
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_MESSAGE =~ /ci-run-complete-pipeline/
       variables:
         DEPLOY_BUILT_CONTAINER: "true"
@@ -568,6 +601,10 @@ get-crane:
       - crane
     when: always
     expire_in: 1 day
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
+    - when: always
 
 nspect-source-scan-x86_64:
   stage: .pre
@@ -580,6 +617,8 @@ nspect-source-scan-x86_64:
     PULSE_SCAN_VULNERABILITY_REPORT: "nspect_${CI_COMMIT_BRANCH}_scan_report.json"
   rules:
     - when: never
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
       variables:
         PULSE_SCAN_OVERRIDE: "true"
@@ -614,6 +653,8 @@ nspect-container-scan-x86_64:
     - ./crane pull ${CONTAINER_IMAGE} /tmp/archive.tar
     - pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN -p .gitlab/runtime-container-policy.json scan --override=true --program-version="Forge-LPR" --is-release=true -i /tmp/archive.tar --sbom json -o
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
 
 promote-images-to-production:
@@ -640,6 +681,8 @@ promote-images-to-production:
     crane copy $ARTIFACTS_DOCKER_IMAGE_AARCH64:$VERSION $ARTIFACTS_DOCKER_IMAGE_AARCH64_PRODUCTION:$VERSION
     crane copy $ARTIFACTS_DOCKER_IMAGE_X86_64:$VERSION $ARTIFACTS_DOCKER_IMAGE_X86_64_PRODUCTION:$VERSION
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
 
 license-checks:
@@ -651,6 +694,8 @@ license-checks:
     - changes:
         - Cargo.lock
         - .license-config.yml
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - if: $CI_COMMIT_TAG
     - if: $CI_PIPELINE_SOURCE != 'merge_request_event'
 
@@ -671,7 +716,119 @@ pages:
     paths:
       - public
   rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
     - changes:
         - book/
     - if: $CI_COMMIT_TAG
     - if: $CI_PIPELINE_SOURCE != 'merge_request_event'
+
+#
+# Build and push the image that contains the dependencies for job 'scheduled-test:auto-deploy-site-controller'
+#
+build-site-auto-deploy-container:
+  extends: build-container
+  rules:
+    - changes:
+        - dev/docker/Dockerfile.site-auto-deploy-container
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: never
+  variables:
+    DOCKER_FILE: $CI_PROJECT_DIR/dev/docker/Dockerfile.site-auto-deploy-container
+    BUILD_DOCKER_IMAGE: $CONTAINER_SITE_AUTO_DEPLOY
+  script:
+    - docker build --add-host=gitlab-master.nvidia.com:10.120.180.120 --file $DOCKER_FILE --tag $BUILD_DOCKER_IMAGE .
+    - docker push $BUILD_DOCKER_IMAGE
+
+#
+# Get the latest versions of carbide and ssh-console from nvcr.io/nvidian/nvforge-devel
+#
+scheduled-test:get-latest-versions:
+  needs:
+    - job: export-docker-json-config
+      optional: false
+      artifacts: true
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: always
+  image:
+    name: golang:1.22
+    entrypoint: [ "" ]
+  variables:
+    TESTABLE_VERSION_PATTERN: '^v\d{4}\.\d{2}-\w+(-\d+-g\w+)*$'
+  before_script:
+    - set -xeuo pipefail
+    - mkdir -p /root/.docker
+    - cp .docker/config.json /root/.docker/config.json
+    - go install github.com/google/go-containerregistry/cmd/crane@v0.19.1
+  script:
+    - CARBIDE_VERSIONS="$(crane ls "${APPLICATION_DOCKER_IMAGE}" | grep -P "${TESTABLE_VERSION_PATTERN}" | sort -V | tail -n 10 | tac)"
+    - BOOT_AARCH64_VERSIONS="$(crane ls "${ARTIFACTS_DOCKER_IMAGE_AARCH64}" | grep -P "${TESTABLE_VERSION_PATTERN}" | sort -V | tail -n 10 | tac)"
+    - BOOT_X86_VERSIONS="$(crane ls "${ARTIFACTS_DOCKER_IMAGE_X86_64}" | grep -P "${TESTABLE_VERSION_PATTERN}" | sort -V | tail -n 10 | tac)"
+    - |
+      LATEST_COMMON_VERSION=""
+      for version in $(echo "${CARBIDE_VERSIONS}"); do
+        if [[ $(echo "${BOOT_AARCH64_VERSIONS}" | grep -c "\<$version\>") -gt 0 ]] && [[ $(echo "${BOOT_X86_VERSIONS}" | grep -c "\<$version\>") -gt 0 ]]; then
+          LATEST_COMMON_VERSION=$version
+          break
+        fi
+      done
+      if [[ -z "${LATEST_COMMON_VERSION}" ]]; then
+        echo "Error: There is no common version across the last 10 versions of nvmetal-carbide, boot-artifacts-aarch64 and boot-artifacts-x86_64."
+        exit 1
+      fi
+    - SSH_CONSOLE_VERSION="$(crane ls "${DEV_NVCR_BASE}"/ssh-console | grep -P "${TESTABLE_VERSION_PATTERN}" | sort -V | tail -n 1)"
+    - |
+      if [[ -z "${SSH_CONSOLE_VERSION}" ]]; then
+        echo "Error: SSH_CONSOLE_VERSION is empty."
+        exit 1
+      fi
+    - echo "LATEST_COMMON_VERSION=${LATEST_COMMON_VERSION}" >> versions.env
+    - echo "SSH_CONSOLE_VERSION=${SSH_CONSOLE_VERSION}" >> versions.env
+  artifacts:
+    reports:
+      dotenv: versions.env
+
+#
+# Auto-deploy the latest versions of carbide and ssh-console to the site under test by updating the `forged` repo
+#
+scheduled-test:auto-deploy-site-controller:
+  needs:
+    - job: scheduled-test:get-latest-versions
+      optional: false
+      artifacts: true
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+      when: always
+  retry:
+    when:
+      - runner_system_failure
+    max: 2
+  image:
+    name: $CONTAINER_SITE_AUTO_DEPLOY
+    entrypoint: [ "" ]
+  variables:
+    # This variable is specified in GitLab UI > Scheduled Pipelines
+    SITE_UNDER_TEST: $SITE_UNDER_TEST
+    VAULT_ADDR: https://prod.vault.nvidia.com
+    VAULT_NAMESPACE: ngc-forge
+    GITLAB_SERVER_URL_NO_PORT: $CI_SERVER_PROTOCOL://$CI_SERVER_HOST
+    FORGED_PROJECT_ID: 90150
+    FORGED_BRANCH: "auto-update-from-carbide-pipeline-${CI_PIPELINE_IID}"
+    FORGED_COMMIT_MSG: "chore: Auto-update ${SITE_UNDER_TEST} to site-controller ${LATEST_COMMON_VERSION}"
+    ARGOCD_SITE_USERNAME: admin
+  before_script:
+    - set -euo pipefail
+    # Cannot overwrite predefined GitLab variables using the 'variables' section, so do it here:
+    - export VAULT_JWT_PATH="auth/jwt/nvidia/gitlab-master/login"
+    - export VAULT_JWT_ROLE="gitlab-ci"
+    - export VAULT_TOKEN="$(vault write -field=token "${VAULT_JWT_PATH}" role="${VAULT_JWT_ROLE}" jwt="${CI_JOB_JWT}")"
+    - export ARGOCD_SITE_PASSWORD="$(vault kv get -field argocd-admin-password secrets/${SITE_UNDER_TEST})"
+    # Parse short site name from full site name
+    - export SHORT_SITE_NAME=$(echo "${SITE_UNDER_TEST}" | cut -d '-' -f 2)
+    - echo "SHORT_SITE_NAME=${SHORT_SITE_NAME}" >> site.env
+  script:
+    - bash .gitlab/update-site-controller.sh
+  artifacts:
+    reports:
+      dotenv: site.env
