fix(otel): Make otel wait for cloud-init completion
## Description
Restores a previous hostname check and also adds an ExecStartPre for all the otel services to wait for cloud-init to complete running.

The cloud-init config options we use look like they should be persisting their hostname change on the DPU, but it doesn't seem to be the case, or there was at least a bug reported in the past that suggests it's not persisting, which means we're waiting for cloud-init to do it for us.  That leaves us with a race between cloud-init completion and otel start.

Adding `ExecStartPre=cloud-init status --wait` will make sure that the otel services don't start until cloud-init is done and won't depend on checking for a specific default hostname value.

I'm also restoring a previous hostname/localhost check from TErickson just for a little extra check.  It shouldn't be necessary, but we could later search logs for the error output over a long time window to confirm that waiting for cloud-init resolved the root of the issue.

## Type of Change
<!-- Check one that best describes this MR -->
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [x] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Related Tickets (Optional)
<!-- If applicable, provide JIRA or/and NVBugs ticket. If none, the MR itself will be referenced in changelog -->
JIRA: <!-- e.g., [FORGE-1234](https://jirasw.nvidia.com/browse/FORGE-1234) or leave blank -->
NVBugs: <!-- e.g., [NVBugs-12345](https://nvbugspro.nvidia.com/bug/12345) or leave blank -->

## Breaking Changes
- [ ] This MR contains breaking changes

<!-- If checked above, describe the breaking changes and migration steps -->

## Testing
<!-- How was this tested? Check all that apply -->
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated  
- [x] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes
<!-- Any additional context, deployment notes, or reviewer guidance -->

See merge request nvmetal/carbide!5083

diff --git a/bluefield/otel/otelcol-wrapper b/bluefield/otel/otelcol-wrapper
--- a/bluefield/otel/otelcol-wrapper
+++ b/bluefield/otel/otelcol-wrapper
@@ -1,5 +1,13 @@
 #!/bin/bash -p
 
+
+$HOSTNAME=$(hostname)
+
+if [[ "$HOSTNAME" == "localhost" ]]; then
+    echo "hostname cannot be 'localhost'"
+    exit 1
+fi
+
 source /etc/otelcol-contrib/otelcol-wrapper-imports
 
 # This should protect us on start-up in the event that bad extension config was left behind.
