Update book for new kubernetes dev process

diff --git a/include/Makefile-bootstrap.toml b/include/Makefile-bootstrap.toml
--- a/include/Makefile-bootstrap.toml
+++ b/include/Makefile-bootstrap.toml
@@ -1,34 +1,62 @@
 [tasks.build-bootstrap-forge-docker]
+category = "Bootstrap Forge Docker"
+workspace = false
+env = { "FORGE_BOOTSTRAP_KIND" = "docker" }
+run_task = "bootstrap_forge"
+
+[tasks.build-bootstrap-forge-kube]
+category = "Bootstrap Forge Kube"
+workspace = false
+env = { "FORGE_BOOTSTRAP_KIND" = "kube" }
+run_task = "bootstrap_forge"
+
+[tasks.bootstrap_forge]
 category = "Bootstrap Forge"
 workspace = false
 script = '''
 #!/usr/bin/env bash
-source include/envrc-docker-compose
-echo $DATABASE_URL
+set -e
+
+source ${REPO_ROOT}/dev/${FORGE_BOOTSTRAP_KIND}-env/envrc
+DATA_PATH=${REPO_ROOT}/dev/${FORGE_BOOTSTRAP_KIND}-env
+
+echo using data path ${DATA_PATH}
 
 echo Populating resource pools
-${REPO_ROOT}/target/debug/forge-admin-cli resource-pool define -f dev/resource_pools.toml
+echo ${REPO_ROOT}/target/debug/forge-admin-cli -c https://${API_SERVER_IP}:${API_SERVER_PORT} resource-pool define -f ${DATA_PATH}/resource_pools.toml
+${REPO_ROOT}/target/debug/forge-admin-cli -c https://${API_SERVER_IP}:${API_SERVER_PORT} resource-pool define -f ${DATA_PATH}/resource_pools.toml
 
-vpc=$(grpcurl -d '{"name":"test_vpc"}' -insecure 127.0.0.1:1079 forge.Forge/CreateVpc | jq ".id.value" | tr -d '"')
-domain=$(grpcurl -d '{"name":"forge.local"}' -insecure 127.0.0.1:1079 forge.Forge/CreateDomain | jq ".id.value" | tr -d '"')
-segment=$(grpcurl -d "{\"name\":\"test\", \"mtu\": 1490, \"prefixes\":[{\"prefix\":\"172.20.0.0/24\",\"gateway\":\"172.20.0.1\",\"reserve_first\":30}], \"subdomain_id\": { \"value\":\"$domain\"}, \"vpc_id\": { \"value\": \"$vpc\"}}" -insecure 127.0.0.1:1079 forge.Forge/CreateNetworkSegment | jq ".id.value" | tr -d '"')
+vpc=$(grpcurl -d '{"name":"test_vpc"}' -insecure $API_SERVER_IP:$API_SERVER_PORT forge.Forge/CreateVpc | jq ".id.value" | tr -d '"')
+echo "vpc: $vpc"
+domain=$(grpcurl -d '{"name":"forge.local"}' -insecure $API_SERVER_IP:$API_SERVER_PORT forge.Forge/CreateDomain | jq ".id.value" | tr -d '"')
+echo "domain: $domain"
+segment=$(grpcurl -d "{\"name\":\"test\", \"mtu\": 1490, \"prefixes\":[{\"prefix\":\"${NET_PREFIX}\",\"gateway\":\"${NET_GATEWAY}\",\"reserve_first\":100}], \"subdomain_id\": { \"value\":\"$domain\"}, \"vpc_id\": { \"value\": \"$vpc\"}}" -insecure $API_SERVER_IP:$API_SERVER_PORT forge.Forge/CreateNetworkSegment | jq ".id.value" | tr -d '"')
+echo "segment: $segment"
 
-RELAY_ADDRESS=$(jq '.relay_address' $REPO_ROOT/dev/grpc-test-data/host_dhcp_discovery.json | tr -d '"')
+RELAY_ADDRESS=$(jq '.relay_address' $DATA_PATH/host_dhcp_discovery.json | tr -d '"')
 echo Relay address: $RELAY_ADDRESS
 echo Segment: $segment
 
-$REPO_ROOT/dev/grpc-test-data/discover_dpu.sh
-psql -t -c "UPDATE vpc_resource_leafs SET loopback_ip_address='$RELAY_ADDRESS' WHERE loopback_ip_address IS NULL;"
+$REPO_ROOT/dev/bin/discover_dpu.sh $API_SERVER_IP $API_SERVER_PORT ${DATA_PATH}
+
+if [ "$FORGE_BOOTSTRAP_KIND" == "kube" ]; then
+  CARBIDE_API_POD=$(kubectl get pod --context minikube --namespace forge-system -l='carbide_api_pod=yes' -o json | jq -r '.items[0].metadata.name')
+  echo "running psql inside pod ${CARBIDE_API_POD}"
+  kubectl exec --context minikube --namespace forge-system -it ${CARBIDE_API_POD} -- \
+    bash -c 'psql postgres://${DATASTORE_USER}:${DATASTORE_PASSWORD}@${DATASTORE_HOST}:${DATASTORE_PORT}/${DATASTORE_NAME} -c "UPDATE vpc_resource_leafs SET loopback_ip_address='"'${RELAY_ADDRESS}'"';"'
+else
+  psql -t -c "UPDATE vpc_resource_leafs SET loopback_ip_address='$RELAY_ADDRESS';"
+fi
 
 echo "Waiting for the network segment to become ready"
-echo "If this step fails, run /dev/grpc-test-data/discover_host.sh manually"
-while [ $(grpcurl -d "{\"id\": {\"value\": \"$segment\"}}" -insecure 127.0.0.1:1079 forge.Forge/FindNetworkSegments | jq ".networkSegments[0].state") != '"READY"' ]; do
+echo "If this step fails, run ${REPO_ROOT}/dev/bin/discover_host.sh manually"
+while [ $(grpcurl -d "{\"id\": {\"value\": \"$segment\"}}" -insecure $API_SERVER_IP:$API_SERVER_PORT forge.Forge/FindNetworkSegments | jq ".networkSegments[0].state") != '"READY"' ]; do
 	echo -n '.'
 	sleep 1
 done
 echo ''
 
-$REPO_ROOT/dev/grpc-test-data/discover_host.sh
+$REPO_ROOT/dev/bin/discover_host.sh $API_SERVER_IP $API_SERVER_PORT ${DATA_PATH}
 '''
 cwd="${REPO_ROOT}"
 
@@ -37,18 +65,21 @@ category = "Bootstrap Forge"
 workspace = false
 script = '''
 #!/usr/bin/env bash
-source include/envrc-docker-compose
-echo "In case you don't want to delete instance for further testing, call script 'dev/grpc-test-data/instance_handling.sh create' and 'dev/grpc-test-data/instance_handling.sh delete'"
-$REPO_ROOT/dev/grpc-test-data/instance_handling.sh
+
+source ${REPO_ROOT}/dev/docker-env/envrc
+echo "In case you don't want to delete instance for further testing, call script 'dev/bin/instance_handling.sh create' and 'dev/bin/instance_handling.sh delete'"
+$REPO_ROOT/dev/bin/instance_handling.sh test ${API_SERVER_IP} ${API_SERVER_PORT}
 '''
 cwd="${REPO_ROOT}"
 
-[tasks.build-bootstrap-forge-kube]
+[tasks.test-instance-forge-kube]
 category = "Bootstrap Forge"
 workspace = false
 script = '''
-vpc=$(grpcurl -d '{"name":"test_vpc"}' -insecure 127.0.0.1:80 forge.Forge/CreateVpc | jq ".id.value" | tr -d '"')
-domain=$(grpcurl -d '{"name":"forge.local"}' -insecure 127.0.0.1:80 forge.Forge/CreateDomain | jq ".id.value" | tr -d '"')
-grpcurl -d "{\"name\":\"test\", \"mtu\": 1490, \"prefixes\":[{\"prefix\":\"172.20.0.0/24\",\"gateway\":\"172.20.0.1\",\"reserve_first\":22}, {\"prefix\":\"::1/128\", \"reserve_first\":0}], \"subdomain_id\": { \"value\":\"$domain\"}, \"vpc_id\": { \"value\": \"$vpc\"}}" -insecure 127.0.0.1:80 forge.Forge/CreateNetworkSegment
+#!/usr/bin/env bash
+
+source ${REPO_ROOT}/dev/kube-env/envrc
+echo "In case you don't want to delete instance for further testing, call script 'dev/bin/instance_handling.sh create' and 'dev/bin/instance_handling.sh delete'"
+$REPO_ROOT/dev/bin/instance_handling.sh test ${API_SERVER_IP} ${API_SERVER_PORT}
 '''
-cwd="${REPO_ROOT}"
+
